OPENAI_API_KEY='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'

GOOGLE_APPLICATION_CREDENTIALS='.streamlit/.google/ultranslator-312fe4951217.json'

GOOGLE_CLOUD_SERVICE_ACCOUNT_AUGURYBOT_AUTHORIZATION_KEY_NUMBER='312fe495121750b7f65f8ef605474a0540bbf342'

# GOOGLE_APPLICATION_CREDENTIALS=.streamlit/.google/ultranslator-312fe4951217.json